## Getting started

In this notebook, we will get started with the Jupyter notebooks and will explore some fundamental Python functions and statements, which will be useful for the relevant coding in this course.

To work with the notebooks in this course, you do not need to install Python in your system. However, we provide references on how to do this at the end of the notebook.

To run each of the following cells, use the keyboard shortcut **SHIFT** + **ENTER**, press the button ``Run`` in the toolbar or find the option ``Cell > Run Cells`` from the menu bar. For more shortcuts, see ``Help > Keyboard Shortcuts``.

Note that this is a brief introduction to Python, which will be useful for this course. Consulting the references at the end of this notebook is highly recommended.

### Conditionals and ``for`` loops

To iterate over a sequence of elements, you can use a ``for`` loop statement.
Observe the following list containing different numbers.

In [2]:
numbers = [-1, 8, -4, 5, 6, 8, 1, 0, 5, 5]

We will return the sum of all values you input in ``numbers`` using a for loop. Note that a for-loop must end with a colon ``:``. 

In [3]:
total = 0
for number in numbers:
    total = total + number

print(total)

33


Instead of ``total = total + numbers``, you can use ``total += numbers`` for conciseness. Now, what if we want to add only the negative numbers? In this case an ``if``-statement is appropriate. Similar to the ``for``-loop, an ``if``-statement must end using ``:``.

In [4]:
total = 0
for number in numbers:
    if number < 0:
        total = total + number
        
print(total)

-5


#### Exercises 
Using ``for`` loops
- Compute how many positive values there are in ``numbers``,
- Compute how many negative values there are in ``numbers``,
- Compute the sum of all the positive numbers.

In [5]:
# Write your functions here. To create a new cell, click on the left side of any cell and press "a" 
# in your keyboard. To delete, press "d" twice.

## Modules

Modules are libraries which extend Python's functionality. Some modules that we will use 

- ``numpy``: adds supports for matrices and includes very useful mathematical functions. 
- ``sympy``: adds support for symbolic computation. This allows us to perform integration, differentiation and other useful operations analytically.
- ``matplotib.pyplot``: adds support for generating plots.

To make them accessible, we need to import them into our working space.

In [5]:
import numpy as np
import sympy as sp
import matplotlib.pyplot as plt

Now we can use their functions. For example, we can compute the square root of a number by using

In [6]:
number = 81
result = np.sqrt(number)

We will now explore some important functions that will come in handy during this course

### Numpy 

#### Generate equally spaced vectors. 

There are several ways to do this. Let's look at the functions ``arange`` and ``linspace``.

- ``arange`` creates a vector from ``start`` to ``end`` using a step. Note that the last value is not included. 
- ``linspace`` creates a vector from ``start`` to ``end`` and divides that range into ``total`` intervals.

In [7]:
start, end, step = 0, 11.0, 1
vec1 = np.arange(start, end, step)

start, end, total = 0, 10.0, 11
vec2 = np.linspace(start, end, total)

We can index these vectors using brackets

In [8]:
vec1[0], vec1[2], vec1[4]

(0.0, 2.0, 4.0)

#### Create and perform operations with matrices and vectors

In [9]:
A = np.zeros((5, 10))         # A 5x10 matrix of zeros
B = np.ones((5, 10))          # A 5x10 matrix of ones
I = np.eye(5)                 # An identity matrix of size 5x5
R = np.random.rand(5, 10)     # A 5x10 matrix of random numbers x in [0, 1]

Now, let's look at some vector/matrix operations. Note that ``*`` is element-wise multiplication and ``@`` implies matrix/vector multiplication. For example, run the following cells and see the output.

In [10]:
R * B                         # Elementwise multiplication Dij = Rij*Bij

array([[0.20544129, 0.21388956, 0.7703515 , 0.92768811, 0.78552326,
        0.14913252, 0.80772225, 0.71967022, 0.44323799, 0.80020939],
       [0.18870998, 0.09648724, 0.77803358, 0.34098545, 0.45587911,
        0.22906041, 0.76240718, 0.55715494, 0.9410092 , 0.8299019 ],
       [0.24679514, 0.58822126, 0.68044615, 0.22881779, 0.12414627,
        0.67745088, 0.04762389, 0.04852383, 0.86368705, 0.14365675],
       [0.14549557, 0.8990288 , 0.9331061 , 0.35945606, 0.76027303,
        0.20032365, 0.08838841, 0.00739851, 0.6149887 , 0.86737212],
       [0.21031502, 0.32748385, 0.68840376, 0.08813859, 0.19555493,
        0.59448497, 0.88784091, 0.35873263, 0.09734105, 0.20854743]])

In [11]:
R @ B.T                       # Matrix multiplication. Dimensions must be right, use .T for transpose

array([[5.82286609, 5.82286609, 5.82286609, 5.82286609, 5.82286609],
       [5.17962899, 5.17962899, 5.17962899, 5.17962899, 5.17962899],
       [3.64936902, 3.64936902, 3.64936902, 3.64936902, 3.64936902],
       [4.87583094, 4.87583094, 4.87583094, 4.87583094, 4.87583094],
       [3.65684313, 3.65684313, 3.65684313, 3.65684313, 3.65684313]])

You can also apply mathematical functions to a complete vector of matrix. Some functions are ``np.sin, np.cos, np.exp ``, for example, we can compute $\sin(2\pi A)$ by

In [12]:
np.sin(2*np.pi*A)

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

#### Exercises
1. Create a vector of ones called ``v1`` with length 10
2. Create a vector of even numbers called ``v2`` starting at 0 with the same length of ``v1``
3. Compute the inner and outer product of these two vectors. 
    1. The inner product of two column vectors can be written $\vec v_1^T \cdot \vec v_2$
    2. The outer product of two column vectors can be written $\vec v_1 \cdot \vec v_2^T$

### Sympy

#### Creating symbolic variables
To create variables $x$, $y$ and $z$, run the following cell. Note that one or more variables can be created in a single line.

In [13]:
x = sp.symbols('x')                        # One at a time
x, y, z = sp.symbols('x y z')              # Multiple at a time

### Creating symbolic functions
Using the variables we created in the previous cell, we will define the function
$$ f(x) = x^4+0.5x^3-x^2+0.1+\sin(x)$$
where the power function in Python is specified with ``**``

In [14]:
f = x**4 + 0.5*x**3 - x**2 + 0.1 + sp.sin(x)

Note that when using symbolic computations, we can use ``sp.sin, sp.cos, sp.exp``, among others.

We can derive or integrate our functions by

In [15]:
fder = sp.diff(f, x)                      # Derivative of f, f'(x)
fint1 = sp.integrate(f, (x, -1, 1))       # Definite integral from -1 to 1
fint2 = sp.integrate(f, x)                # Indefinite integral

We can evaluate our expressions at a point, for exaple $f(1)$ can be written as

In [16]:
fder.subs(x, 1)

cos(1) + 3.5

#### Exercises
1. Create the function $f(x) = e^{-40(x-0.5)^2}$
2. Compute the indefinite integral of $f(x)$
3. Compute the integral $\int_{0}^{1} f(x)dx$

### Matplotlib

In order to plot our functions, we will first create a set of vectors.

1. Create an equally spaced vector called ``X`` from $0$ to $2\pi$ with 50 elements.
2. Compute the vector $\vec y=\sin(\vec x)$

In [79]:
X = 
Y = 

To plot a simple curve, we use ``plt.plot(X, Y)``

In [81]:
# Plot X vs Y

You may add an additional curve to the plot simply by defining new values of ``Y`` and plotting them. For example, define $\vec y_2 = \cos(\pi)$

In [ ]:
Y2 = 

In [ ]:
# Plot X vs Y2. The plot above will update. To create a new plot, you must use plt.figure() before plotting

### Additional References
1. For general Python installation and programming, Corey Schafer provides a handful of videos on Youtube. We list some of the relevant videos
    1. Installing Python (Mac OS & Windows) https://youtu.be/YYXdXT2l-Gg
    2. Conditional statements https://youtu.be/DZwmZ8Usvnk
    3. For loops and iterations https://youtu.be/6iF8Xb7Z3wQ
    4. Introduction to Matplotlib https://youtu.be/UO98lJQ3QGI
2. Derek Banas provides a crash course for Python in a single video https://youtu.be/H1elmMBnykA
2. Other useful references can be found in the appropriate module documentations
    1. Numpy basics https://numpy.org/doc/1.18/user/basics.html
    2. Sympy basics https://docs.sympy.org/latest/tutorial/basic_operations.html
 